# Generated by Django 5.2.7 on 2025-10-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentary', '0002_book_commentary_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
