# Generated by Django 5.2.7 on 2025-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentary', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='verse',
            field=models.CharField(max_length=10),
        ),
    ]
